version: '3.4'

services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ --config=/etc/collector.yml ]
    volumes:
      - ./collector.yml:/etc/collector.yml
    env_file:
      - ./collector.env
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "8888:8888" # Collector Prometheus port
